version: '3'
services:
  django:
    environment:
      - IS_DOCKER=True
      - ENVIRONMENT=${ENVIRONMENT}
      - NGROK_API_KEY=${NGROK_API_KEY}
      - NGROK_URL=${NGROK_URL}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
      - "6800:6800"
    depends_on:
      - db
    networks:
      - backend
    network_mode: bridge
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./../static:/app/static
    depends_on:
      - django
    networks:
      - backend
  db:
    image: postgis/postgis:14-3.3
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - backend
volumes:
  db_data:
  staging_db_data:
  production_db_data:
networks:
  backend:
