# Generated by Django 4.2.2 on 2023-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_scrapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='community',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
